Q = orth(randn(10,10));
A = Q*diag(1:10)*inv(Q);
maxit = 1000;
tol   = 1.e-6; 
[x,mu,RelErr,Ratio] = power_method(A,maxit,tol);
%% Plots
xline = linspace(1,numel(RelErr),numel(RelErr));
figure(1)
semilogy(xline,RelErr,'--sk',...
    'LineWidth',2,...
    'MarkerSize',5,...
    'MarkerEdgeColor','#0072BD',...
    'MarkerFaceColor','#0072BD')
hold on
grid on
semilogy(xline,Ratio,'--^k',...
    'LineWidth',2,...
    'MarkerSize',5,...
    'MarkerEdgeColor','#D95319',...
    'MarkerFaceColor','#D95319')
legend('|\lambda_2-\mu_k|/|\lambda_1|','|\lambda_2/\lambda_1|^k')
title('Convergence power method on A symmetric')
xlabel('Iter. number')

%% Test 2: same as before but with A non-symmetric
Q = randn(10,10);
A = Q*diag(1:10)*inv(Q);
maxit = 1000;
tol   = 1.e-6; 
[x,mu,RelErr,Ratio] = power_method(A,maxit,tol);
%% Plots
xline = linspace(1,numel(RelErr),numel(RelErr));
figure(2)
semilogy(xline,RelErr,'--sk',...
    'LineWidth',2,...
    'MarkerSize',5,...
    'MarkerEdgeColor','#0072BD',...
    'MarkerFaceColor','#0072BD')
hold on
grid on
semilogy(xline,Ratio,'--^k',...
    'LineWidth',2,...
    'MarkerSize',5,...
    'MarkerEdgeColor','#D95319',...
    'MarkerFaceColor','#D95319')
legend('|\lambda_2-\mu_k|/|\lambda_1|','|\lambda_2/\lambda_1|^k')
title('Convergence power method on A non-symmetric')
xlabel('Iter. number')
