% Same test ad before but comparing also with Conjugate Gradients.
n = 40;
A = gallery('poisson',n);
b = ones(size(A,1),1);
tol   = 1.e-6;
maxit = 1000;
x0    = zeros(size(A,1),1);
[Jx,Jres,Jits] = Jacobi(A,b,tol,maxit,x0); % Jacobi
[Gx,Gres,Gits] = Gauss_Seidel(A,b,tol,maxit,x0); % Gauss-Seidel
% CG starts from x0 = 0 by default. 
[X,FLAG,RELRES,ITER,RESVEC] = pcg(A,b,tol,maxit); % CG

figure(1)
semilogy(linspace(0,Jits,Jits+1),Jres,'--sk',...
    'LineWidth',2,...
    'MarkerSize',5,...
    'MarkerEdgeColor','#0072BD',...
    'MarkerFaceColor','#0072BD')
hold on
grid on
semilogy(linspace(0,Gits,Gits+1),Gres,'--^k',...
    'LineWidth',2,...
    'MarkerSize',5,...
    'MarkerEdgeColor','#D95319',...
    'MarkerFaceColor','#D95319')
semilogy(linspace(0,ITER,ITER+1),RESVEC,'--ok',...
    'LineWidth',2,...
    'MarkerSize',5,...
    'MarkerEdgeColor','#EDB120',...
    'MarkerFaceColor','#EDB120')

legend('Jacobi','Gauss-Seidel','Conj. Gradients','Location','southeast')
title('Convergence of Jacobi, Gauss-Seidel and CG')
xlabel('iter. number')
ylabel('log_{10}(|| b - Ax^k ||_{l^2})')
